// Code generated by "stringer -type=Code"; DO NOT EDIT

package command

import "fmt"

const _Code_name = "M_NULM_ADRM_PWDM_FILEM_OKM_EOBM_GOTM_ERRM_BSYM_GETM_SKIP"

var _Code_index = [...]uint8{0, 5, 10, 15, 21, 25, 30, 35, 40, 45, 50, 56}

func (i Code) String() string {
	if i >= Code(len(_Code_index)-1) {
		return fmt.Sprintf("Code(%d)", i)
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
