// Code generated by "stringer -type=cState"; DO NOT EDIT

package mailer

import "fmt"

const _cState_name = "cConnInitcWaitConncSendPasswdcWaitAddrcAuthRemotecIfSecurecWaitOKcOptscPwdAckcInitTransfercSwitchcRecivecTransmit"

var _cState_index = [...]uint8{0, 9, 18, 29, 38, 49, 58, 65, 70, 77, 90, 97, 104, 113}

func (i cState) String() string {
	if i >= cState(len(_cState_index)-1) {
		return fmt.Sprintf("cState(%d)", i)
	}
	return _cState_name[_cState_index[i]:_cState_index[i+1]]
}
