// Code generated by "stringer -type=ctxKey"; DO NOT EDIT

package mailer

import "fmt"

const _ctxKey_name = "ctxClientctxLogctxConn"

var _ctxKey_index = [...]uint8{0, 9, 15, 22}

func (i ctxKey) String() string {
	if i < 0 || i >= ctxKey(len(_ctxKey_index)-1) {
		return fmt.Sprintf("ctxKey(%d)", i)
	}
	return _ctxKey_name[_ctxKey_index[i]:_ctxKey_index[i+1]]
}
