// Code generated by "stringer -type=rxState"; DO NOT EDIT

package mailer

import "fmt"

const _rxState_name = "rxWaitFrxAccFrxReceDrxWriteDrxEOBrxDone"

var _rxState_index = [...]uint8{0, 7, 13, 20, 28, 33, 39}

func (i rxState) String() string {
	if i >= rxState(len(_rxState_index)-1) {
		return fmt.Sprintf("rxState(%d)", i)
	}
	return _rxState_name[_rxState_index[i]:_rxState_index[i+1]]
}
