// Code generated by "stringer -type=txState"; DO NOT EDIT

package mailer

import "fmt"

const _txState_name = "txGNFtxTryRtxReadStxWLAtxDone"

var _txState_index = [...]uint8{0, 5, 11, 18, 23, 29}

func (i txState) String() string {
	if i >= txState(len(_txState_index)-1) {
		return fmt.Sprintf("txState(%d)", i)
	}
	return _txState_name[_txState_index[i]:_txState_index[i+1]]
}
